language: python
python:
  - "3.6"
# command to install dependencies
# all needed
install:
  - pip install beautifulsoup4==4.7.1
  - pip install  requests==2.21.0
  - pip install gunicorn==19.9.0

script:
  # command to run tests
  - python -m unittest tests.test_RequestHandler
  - cd src
  - python main.py